from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("compliance", "0005_remove_fiat_transaction_and_high_risk_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertproceduretemplate",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("large_transaction", "Large Transaction (≥AUD 10,000)"),
                    ("rapid_transactions", "Rapid Transactions (5+ in 1 hour)"),
                    ("structuring", "Structuring Pattern"),
                    ("high_aggregate_volume", "High Aggregate Volume (≥AUD 50,000/30 days)"),
                    ("dormant_reactivation", "Dormant Account Reactivation (90+ days)"),
                    ("pattern_deviation", "Material Pattern Deviation (3x average)"),
                    ("round_amounts", "Round Amount Transactions"),
                    ("new_customer_sof", "New Customer SOF Required"),
                    ("extreme_risk_transaction", "Extreme Risk Customer Transaction"),
                    ("high_risk_wallet", "High-Risk Wallet Address"),
                    ("sanctioned_address", "Sanctioned Address"),
                    ("mixer_tumbler", "Mixer/Tumbler Involvement"),
                    ("darknet_association", "Darknet Association"),
                    ("ransomware_association", "Ransomware Association"),
                    ("adverse_media_serious", "Adverse Media (Serious)"),
                    ("adverse_media_minor", "Adverse Media (Minor)"),
                    ("pep_limit_breach", "PEP Hard Limit Breach"),
                    ("info_discrepancy", "Customer Information Discrepancy"),
                    ("failed_documentation", "Failed Documentation Request"),
                    ("multiple_alerts", "Multiple Alerts (3+) Same Customer"),
                    ("sanctions_match", "Sanctions Match"),
                    ("pep_match", "PEP Match"),
                    ("watchlist_match", "Watchlist Match"),
                    ("law_enforcement", "Law Enforcement Inquiry"),
                    ("terrorism_financing", "Terrorism Financing Indicators"),
                    ("sanctions_list_update", "New Sanctions List Publication"),
                    ("periodic_review", "Periodic Review Due"),
                    ("manual", "Manual Alert"),
                ],
                help_text="The alert type this template applies to",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="compliancealert",
            name="alert_type",
            field=models.CharField(
                choices=[
                    ("large_transaction", "Large Transaction (≥AUD 10,000)"),
                    ("rapid_transactions", "Rapid Transactions (5+ in 1 hour)"),
                    ("structuring", "Structuring Pattern"),
                    ("high_aggregate_volume", "High Aggregate Volume (≥AUD 50,000/30 days)"),
                    ("dormant_reactivation", "Dormant Account Reactivation (90+ days)"),
                    ("pattern_deviation", "Material Pattern Deviation (3x average)"),
                    ("round_amounts", "Round Amount Transactions"),
                    ("new_customer_sof", "New Customer SOF Required"),
                    ("extreme_risk_transaction", "Extreme Risk Customer Transaction"),
                    ("high_risk_wallet", "High-Risk Wallet Address"),
                    ("sanctioned_address", "Sanctioned Address"),
                    ("mixer_tumbler", "Mixer/Tumbler Involvement"),
                    ("darknet_association", "Darknet Association"),
                    ("ransomware_association", "Ransomware Association"),
                    ("adverse_media_serious", "Adverse Media (Serious)"),
                    ("adverse_media_minor", "Adverse Media (Minor)"),
                    ("pep_limit_breach", "PEP Hard Limit Breach"),
                    ("info_discrepancy", "Customer Information Discrepancy"),
                    ("failed_documentation", "Failed Documentation Request"),
                    ("multiple_alerts", "Multiple Alerts (3+) Same Customer"),
                    ("sanctions_match", "Sanctions Match"),
                    ("pep_match", "PEP Match"),
                    ("watchlist_match", "Watchlist Match"),
                    ("law_enforcement", "Law Enforcement Inquiry"),
                    ("terrorism_financing", "Terrorism Financing Indicators"),
                    ("sanctions_list_update", "New Sanctions List Publication"),
                    ("periodic_review", "Periodic Review Due"),
                    ("manual", "Manual Alert"),
                ],
                max_length=50,
            ),
        ),
    ]
