REVIEW_GREEN = "GREEN"
REVIEW_RED = "RED"
REVIEW_YELLOW = "YELLOW"

REVIEW_RESULT_CHOICES = [
    (REVIEW_GREEN, "Approved"),
    (REVIEW_RED, "Rejected"),
    (REVIEW_YELLOW, "Retry"),
]

STATUS_INIT = "init"
STATUS_PENDING = "pending"
STATUS_QUEUED = "queued"
STATUS_COMPLETED = "completed"
STATUS_ON_HOLD = "onHold"
STATUS_PRECHECKED = "prechecked"

VERIFICATION_STATUS_CHOICES = [
    (STATUS_INIT, "Initialized"),
    (STATUS_PENDING, "Pending Review"),
    (STATUS_QUEUED, "Queued for Review"),
    (STATUS_COMPLETED, "Review Completed"),
    (STATUS_ON_HOLD, "On Hold"),
    (STATUS_PRECHECKED, "Pre-checked"),
]

PROVIDER_KYCAID = "kycaid"
PROVIDER_SUMSUB = "sumsub"

KYC_PROVIDER_CHOICES = [
    (PROVIDER_SUMSUB, "Sumsub"),
    (PROVIDER_KYCAID, "KYCAID"),
]

KYCAID_EVENT_VERIFICATION_COMPLETED = "VERIFICATION_COMPLETED"
KYCAID_EVENT_VERIFICATION_STATUS_CHANGED = "VERIFICATION_STATUS_CHANGED"
KYCAID_EVENT_DATABASE_SCREENING = "DATABASE_SCREENING"

KYCAID_VERIFICATION_STATUSES = {
    "unused": STATUS_INIT,
    "pending": STATUS_PENDING,
    "completed": STATUS_COMPLETED,
}
KYCAID_APPLICANT_RESULTS = {
    "valid": REVIEW_GREEN,
    "invalid": REVIEW_RED,
}

SCREENING_REJECTION_LABELS = frozenset(
    {
        "PEP",
        "SANCTIONS",
        "COMPROMISED_PERSONS",
        "ADVERSE_MEDIA",
        "CRIMINAL",
        "BLOCKLIST",
        "RESTRICTED_PERSON",
        "COMPROMISED_PERSON",
    }
)
NEUTRAL_REJECTION_LABEL = "UNABLE_TO_VERIFY"

SUMSUB_EVENT_APPLICANT_CREATED = "applicantCreated"
SUMSUB_EVENT_APPLICANT_PENDING = "applicantPending"
SUMSUB_EVENT_APPLICANT_REVIEWED = "applicantReviewed"
SUMSUB_EVENT_APPLICANT_ON_HOLD = "applicantOnHold"
