WHITELIST_STATUS_WHITELISTED = "whitelisted"
WHITELIST_STATUS_NOT_WHITELISTED = "not_whitelisted"
WHITELIST_STATUS_UNKNOWN = "unknown"
WHITELIST_RECOVERY_LIMIT = 100
WHITELIST_REFRESH_LIMIT = 100
WHITELIST_REMOVAL_RETRY_SECONDS = 300
WALLET_REFRESH_DELAY_SECONDS = 60
WHITELIST_NO_EXPIRY = 2**64 - 1

WHITELIST_STATUS_CHOICES = [
    WHITELIST_STATUS_WHITELISTED,
    WHITELIST_STATUS_NOT_WHITELISTED,
    WHITELIST_STATUS_UNKNOWN,
]
