PROJECT_MIGRATIONS = frozenset(
    {
        ("assets", "0001_initial"),
        ("assets", "0002_add_ledova_aaud_asset"),
        ("assets", "0003_rename_aaud_asset"),
        ("assets", "0004_deactivate_unsupported_assets"),
        ("assets", "0005_add_asset_chain_deployment"),
        ("assets", "0006_populate_chain_deployments"),
        ("assets", "0007_remove_asset_chain_contract"),
        ("assets", "0008_asset_is_verified"),
        ("assets", "0009_verify_supported_assets_cleanup_spam"),
        ("assets", "0010_alter_asset_asset_type_alter_asset_current_price_and_more"),
        ("assets", "0011_add_exchange_rate_model"),
        ("assets", "0012_audy_base_deployment"),
        ("assets", "0013_price_provenance"),
        ("assets", "0014_native_chain_deployments"),
        ("authentication", "0001_initial"),
        ("authentication", "0002_authsession_refreshcredential"),
        ("authentication", "0003_customuser_v2_email_constraints"),
        ("authentication", "0004_v2_challenge_schema"),
        ("authentication", "0005_auth_del_superseded_proof_shapes"),
        ("authentication", "0006_delete_v2_challenge_models"),
        ("authentication", "0007_delete_authsession_refreshcredential"),
        ("authentication", "0008_delete_usertoken"),
        ("authentication", "0009_otp_attempts_drop_unused_columns"),
        ("blockchain", "0001_initial"),
        ("blockchain", "0002_alter_blockchaintransaction_tx_type"),
        ("blockchain", "0003_delete_contractdeployment"),
        ("blockchain", "0004_durable_outgoing"),
        ("blockchain", "0005_legacy_outgoing_inventory"),
        ("blockchain", "0006_signer_admission"),
        ("blockchain", "0007_transaction_outgoing_operation"),
        ("blockchain", "0008_fresh_signer_bootstrap"),
        ("companies", "0001_initial"),
        ("companies", "0002_company_owner_required"),
        ("companies", "0003_delete_review_and_signature_models"),
        ("companies", "0004_company_additional_info_response"),
        ("companies", "0005_company_is_open_to_investors"),
        ("companies", "0006_company_document_private_storage"),
        ("companies", "0007_alter_company_abn_alter_company_acn"),
        ("companies", "0008_company_registry_verification"),
        ("companies", "0009_document_verification"),
        ("companies", "0010_company_pack"),
        ("companies", "0011_remove_company_api_key"),
        ("companies", "0012_company_authority_request"),
        ("companies", "0013_company_authority_request_withdrawal"),
        ("companies", "0014_authority_request_capabilities_refuse_null"),
        ("companies", "0015_self_declared_company_appointments"),
        ("companies", "0016_appointee_keyed_appointments"),
        ("companies", "0017_company_team_invitations"),
        ("companies", "0018_team_invitation_admission_guards"),
        ("companies", "0019_legacy_owner_appointments"),
        ("companies", "0020_company_administration"),
        ("companies", "0021_company_activation"),
        ("companies", "0022_company_wallet_lock_order"),
        ("compliance", "0001_initial"),
        ("compliance", "0002_initial"),
        ("compliance", "0003_add_provider_field"),
        ("compliance", "0004_remove_sumsub_transaction_id"),
        ("compliance", "0005_remove_fiat_transaction_and_high_risk_country"),
        ("compliance", "0006_pep_and_watchlist_match_alerts"),
        ("compliance", "0007_approved_pep_without_category"),
        ("documents", "0001_initial"),
        ("documents", "0002_document_private_storage"),
        ("documents", "0003_documentread_document_attached_at_and_more"),
        ("feature_flags", "0001_initial"),
        ("feature_flags", "0002_add_trading_enabled_flag"),
        ("feature_flags", "0003_enable_trading_by_default"),
        ("offerings", "0001_initial"),
        ("offerings", "0002_subscription"),
        ("offerings", "0003_subscription_tx_hash_case_insensitive"),
        ("offerings", "0004_protect_the_offering_token"),
        ("offerings", "0005_r0_owner_columns"),
        ("offerings", "0006_trigger_follows_and_refuses"),
        ("offerings", "0007_subscription_step_times"),
        ("offerings", "0008_subscription_snapshots"),
        ("offerings", "0009_published_documents_stay"),
        ("offerings", "0010_company_eligibility_admission"),
        ("operators", "0001_initial"),
        ("operators", "0002_remove_operator_deployment_mode"),
        ("portfolios", "0001_initial"),
        ("portfolios", "0002_initial"),
        ("portfolios", "0003_remove_portfolio_template_and_target_asset_allocation"),
        ("portfolios", "0004_delete_assetallocation"),
        ("portfolios", "0005_delete_portfoliosnapshot"),
        ("shared", "0001_initial"),
        ("shared", "0002_drop_celery_tables"),
        ("shared", "0003_rls_roles_and_grants"),
        ("shared", "0004_rls_policies"),
        ("shared", "0005_rls_principal_missing_ok"),
        ("shared", "0006_account_insert_by_director"),
        ("shared", "0007_review_request_policies"),
        ("shared", "0008_scoped_role_table_grants"),
        ("shared", "0009_policies_require_a_principal"),
        ("shared", "0010_policies_for_the_tables_that_had_none"),
        ("shared", "0011_the_helper_names_the_principal"),
        ("shared", "0012_operator_creates_matches"),
        ("shared", "0013_policies_without_the_dropped_tables"),
        ("shared", "0014_policies_without_notification_preferences"),
        ("shareholders", "0001_publications"),
        ("shareholders", "0002_publication_names_its_company_and_class"),
        ("shareholders", "0003_resolutions"),
        ("shareholders", "0004_distributions"),
        ("shareholders", "0005_publication_event_preimage"),
        ("shareholders", "0006_publication_to_a_paused_class"),
        ("tokens", "0001_initial"),
        ("tokens", "0002_yield_token_and_nav"),
        ("tokens", "0003_unify_mint_request"),
        ("tokens", "0004_seed_ausg_yield_token"),
        ("tokens", "0005_rename_token_issuance_to_share_issuance"),
        ("tokens", "0006_rename_tokens_stab_status_4c5fd9_idx_tokens_mint_status_99ebab_idx_and_more"),
        ("tokens", "0007_stablecoin_reserve_fields"),
        ("tokens", "0008_share_issuance_request"),
        ("tokens", "0009_transferorder_ownership"),
        ("tokens", "0010_transferorder_bind_legacy_orders"),
        ("tokens", "0011_transferorder_owner_required"),
        ("tokens", "0012_reviewable_request"),
        ("tokens", "0013_remove_transferorder_signature_request"),
        ("tokens", "0014_settlement_asset_columns"),
        ("tokens", "0015_fold_stablecoin_into_asset"),
        ("tokens", "0016_drop_stablecoin"),
        ("tokens", "0017_share_token_chain"),
        ("tokens", "0018_protect_the_register_spine"),
        ("tokens", "0019_signing_challenge"),
        ("tokens", "0020_shareissuance_identity_stamped_at_and_more"),
        ("tokens", "0021_modification_log_names_its_challenge"),
        ("tokens", "0022_swap_nonce_is_unique"),
        ("tokens", "0023_r0_owner_columns"),
        ("tokens", "0024_r0_sharetoken_owner"),
        ("tokens", "0025_a_token_cannot_change_company"),
        ("tokens", "0026_one_capital_increase_in_flight"),
        ("tokens", "0029_execution_notes"),
        ("tokens", "0030_superseded_capital_increase"),
        ("tokens", "0031_share_tokens_have_zero_decimals"),
        ("tokens", "0032_former_holders"),
        ("tokens", "0033_the_fold_records_where_it_reached"),
        ("tokens", "0034_shareissuance_mint_journal"),
        ("tokens", "0035_trading_state_invariants"),
        ("tokens", "0036_swap_expiry_eligibility"),
        ("tokens", "0037_order_submissions"),
        ("tokens", "0038_order_action_submissions"),
        ("tokens", "0039_swap_settlement_context"),
        ("tokens", "0040_swap_parent_identity"),
        ("tokens", "0041_drop_the_token_owner_no_policy_reads"),
        ("tokens", "0042_mint_request_operations"),
        ("tokens", "0043_token_deployment"),
        ("tokens", "0044_token_deployment_guards"),
        ("tokens", "0045_capital_increase_execution"),
        ("tokens", "0046_capital_execution_guards"),
        ("tokens", "0047_issuance_execution"),
        ("tokens", "0048_issuance_execution_guards"),
        ("tokens", "0049_swap_approval_phase"),
        ("tokens", "0050_swap_approval_guards"),
        ("tokens", "0051_pause_change"),
        ("tokens", "0052_pause_change_guards"),
        ("tokens", "0053_nav_update_recovery"),
        ("tokens", "0054_nav_update_guards"),
        ("tokens", "0055_order_submission_settlement_refusal"),
        ("tokens", "0056_hold_legacy_swaps"),
        ("tokens", "0057_swap_execution_guards"),
        ("tokens", "0058_swap_finality_completion"),
        ("tokens", "0059_swap_approval_submission"),
        ("tokens", "0060_order_submission_settlement_chain_refusal"),
        ("tokens", "0061_swap_approval_recovery_index"),
        ("tokens", "0062_register_foundation"),
        ("tokens", "0063_swap_finalized_receipt"),
        ("tokens", "0064_reviewed_register_corrections"),
        ("tokens", "0065_register_opening"),
        ("tokens", "0066_issuance_finality_and_boundary_history"),
        ("tokens", "0067_register_wallet_links"),
        ("tokens", "0068_completion_transaction_index"),
        ("tokens", "0069_opening_mapping_values"),
        ("tokens", "0070_register_reconciliation"),
        ("tokens", "0071_register_export_audit"),
        ("tokens", "0072_register_import"),
        ("tokens", "0073_register_instructions"),
        ("tokens", "0074_register_inspection_copies"),
        ("tokens", "0075_register_certificates"),
        ("tokens", "0076_transfer_instructions"),
        ("tokens", "0077_import_opening"),
        ("tokens", "0078_register_notice_figures"),
        ("tokens", "0079_order_submission_eligibility_refusal"),
        ("tokens", "0080_company_pack"),
        ("tokens", "0081_held_orders_and_retired_statuses"),
        ("tokens", "0082_company_eligibility_admission"),
        ("tokens", "0083_company_register_imports"),
        ("tokens", "0084_company_register_import_guards"),
        ("tokens", "0085_company_register_corrections"),
        ("tokens", "0086_company_register_correction_guards"),
        ("tokens", "0087_company_discrepancy_acknowledgements"),
        ("tokens", "0088_company_register_openings"),
        ("tokens", "0089_company_register_opening_guards"),
        ("tokens", "0090_company_particulars_changes"),
        ("tokens", "0091_company_particulars_change_guards"),
        ("tokens", "0092_company_register_wallet_links"),
        ("tokens", "0093_company_register_wallet_link_guards"),
        ("tokens", "0094_company_register_grants"),
        ("tokens", "0095_company_register_grant_guards"),
        ("tokens", "0096_company_register_transfers"),
        ("tokens", "0097_company_register_transfer_guards"),
        ("tokens", "0098_company_register_deployments"),
        ("tokens", "0099_company_register_deployment_guards"),
        ("tokens", "0100_company_register_issue_instructions"),
        ("tokens", "0101_company_register_issue_guards"),
        ("tokens", "0102_company_register_capital_increases"),
        ("tokens", "0103_company_register_capital_guards"),
        ("tokens", "0104_company_register_pause_changes"),
        ("tokens", "0105_company_register_pause_guards"),
        ("tokens", "0106_company_register_paid_issues"),
        ("tokens", "0107_company_register_paid_issue_guards"),
        ("users", "0001_initial"),
        ("users", "0002_remove_userprofile_investor_type"),
        ("users", "0003_alter_userpreferences_preferred_onramp_provider"),
        ("users", "0004_create_notification_model"),
        ("users", "0005_add_kyc_provider_fields"),
        ("users", "0006_populate_kyc_provider_data"),
        ("users", "0007_userprofile_residence_country"),
        ("users", "0008_alter_userprofile_sumsub_review_answer_and_more"),
        ("users", "0009_remove_banxa_coinbase_onramp_provider"),
        ("users", "0010_remove_userpreferences_preferred_onramp_provider"),
        ("users", "0011_delete_widget"),
        ("users", "0012_useraccount_role"),
        ("users", "0013_add_theme_to_user_preferences"),
        ("users", "0014_alter_userpreferences_theme"),
        ("users", "0015_add_display_currency_preference"),
        ("users", "0016_remove_userprofile_duplicate_kyc_columns"),
        ("users", "0017_delete_waitlist"),
        ("users", "0018_investor_classification"),
        ("users", "0019_alter_investorclassification_status_and_more"),
        ("users", "0020_r0_owner_columns"),
        ("users", "0021_trigger_types_from_the_column"),
        ("users", "0022_drop_the_owner_columns_no_policy_reads"),
        ("users", "0023_one_account_per_person"),
        ("users", "0024_remove_useraccount_director"),
        ("users", "0025_remove_unread_preferences"),
        ("users", "0026_delete_favouriteasset"),
        ("users", "0027_transaction_alerts_on_user_preferences"),
        ("users", "0028_remove_theme_and_selected_portfolio"),
        ("users", "0029_first_activation_date"),
        ("users", "0029_kyc_results_in_the_fields_choices"),
        ("users", "0030_join_activation_and_kyc_results"),
        ("users", "0031_protected_identity_results"),
        ("users", "0032_company_eligibility_records"),
        ("users", "0033_company_eligibility_guards"),
        ("users", "0034_company_eligibility_consumption"),
        ("users", "0035_retire_staff_source_review"),
        ("wallets", "0001_initial"),
        ("wallets", "0002_wallet_wallet_type"),
        ("wallets", "0003_update_fiat_transaction_provider_to_transak"),
        ("wallets", "0004_wallet_is_operator"),
        ("wallets", "0005_alter_holdingsnapshot_snapshot_reason"),
        ("wallets", "0006_delete_fiattransaction_drop_unread_columns"),
        ("wallets", "0007_transaction_deducted_amount_transaction_deducted_fee"),
        ("wallets", "0008_r0_owner_column"),
        ("wallets", "0009_trigger_follows_and_refuses"),
        ("wallets", "0010_durable_state_for_a_submitted_transaction"),
        ("wallets", "0011_wallet_verification_challenge_issued_at"),
        ("wallets", "0012_balance_versions"),
        ("wallets", "0013_signing_preference"),
        ("wallets", "0014_wallet_network_identity"),
        ("wallets", "0015_transaction_imported_from_history"),
        ("wallets", "0016_wallet_submission"),
        ("wallets", "0017_bitcoin_submission"),
        ("wallets", "0018_global_submission_identity"),
        ("wallets", "0019_chain_observations"),
        ("wallets", "0020_transaction_monitoring_completed_at"),
        ("wallets", "0021_transaction_finality_observation"),
        ("wallets", "0022_delete_holdingsnapshot"),
        ("wallets", "0023_transaction_market_value_aud"),
        ("wallets", "0024_wallet_possession_proof"),
        ("wallets", "0025_wallet_possession_proof_guards"),
        ("whitelist", "0001_initial"),
        ("whitelist", "0002_whitelistentry_treasury_addresses"),
        ("whitelist", "0003_whitelistentry_unique_treasury_address"),
        ("whitelist", "0004_failure_reconciled_at"),
        ("whitelist", "0005_whitelist_change"),
        ("whitelist", "0006_whitelist_change_guards"),
        ("whitelist", "0007_per_company_approvals"),
        ("whitelist", "0008_classification_refresh_authority"),
        ("whitelist", "0009_company_eligibility_invalidation"),
        ("whitelist", "0010_company_wallet_instructions"),
        ("whitelist", "0011_company_wallet_instruction_guards"),
    }
)

VENDOR_MIGRATIONS = frozenset(
    {
        ("admin", "0001_initial"),
        ("admin", "0002_logentry_remove_auto_add"),
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("auth", "0001_initial"),
        ("auth", "0002_alter_permission_name_max_length"),
        ("auth", "0003_alter_user_email_max_length"),
        ("auth", "0004_alter_user_username_opts"),
        ("auth", "0005_alter_user_last_login_null"),
        ("auth", "0006_require_contenttypes_0002"),
        ("auth", "0007_alter_validators_add_error_messages"),
        ("auth", "0008_alter_user_username_max_length"),
        ("auth", "0009_alter_user_last_name_max_length"),
        ("auth", "0010_alter_group_name_max_length"),
        ("auth", "0011_update_proxy_permissions"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0001_initial"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("procrastinate", "0001_initial"),
        ("procrastinate", "0002_drop_started_at_column"),
        ("procrastinate", "0003_drop_started_at_column"),
        ("procrastinate", "0004_drop_procrastinate_version_table"),
        ("procrastinate", "0005_fix_procrastinate_fetch_job"),
        ("procrastinate", "0006_fix_trigger_status_events_insert"),
        ("procrastinate", "0007_add_queueing_lock_column"),
        ("procrastinate", "0008_close_fetch_job_race_condition"),
        ("procrastinate", "0009_add_defer_job_function"),
        ("procrastinate", "0010_add_procrastinate_periodic_defers"),
        ("procrastinate", "0011_add_foreign_key_index"),
        ("procrastinate", "0012_add_locks_to_periodic_defer"),
        ("procrastinate", "0013_fix_procrastinate_defer_periodic_job"),
        ("procrastinate", "0014_add_finish_job_and_retry_job_functions"),
        ("procrastinate", "0015_add_trigger_on_job_deletion"),
        ("procrastinate", "0016_delete_finished_jobs"),
        ("procrastinate", "0017_add_checks_to_finish_job"),
        ("procrastinate", "0018_add_checks_to_retry_job"),
        ("procrastinate", "0019_fix_finish_job_compat_issue"),
        ("procrastinate", "0020_add_index_on_procrastinate_jobs"),
        ("procrastinate", "0021_add_kwargs_to_defer_periodic_job"),
        ("procrastinate", "0022_null_locks_excluded"),
        ("procrastinate", "0023_remove_old_finish_job_function"),
        ("procrastinate", "0024_job_id_bigint"),
        ("procrastinate", "0025_add_models"),
        ("procrastinate", "0026_add_job_priority"),
        ("procrastinate", "0027_add_periodic_job_priority"),
        ("procrastinate", "0028_add_cancel_states"),
        ("procrastinate", "0029_add_additional_params_to_retry_job"),
        ("procrastinate", "0030_alter_procrastinateevent_options"),
        ("procrastinate", "0031_add_indexes_for_fetch_job"),
        ("procrastinate", "0032_pre_cancel_notification"),
        ("procrastinate", "0033_post_cancel_notification"),
        ("procrastinate", "0034_pre_add_heartbeat"),
        ("procrastinate", "0035_post_add_heartbeat"),
        ("procrastinate", "0036_add_worker_model"),
        ("procrastinate", "0037_pre_batch_defer_jobs"),
        ("procrastinate", "0038_post_batch_defer_jobs"),
        ("procrastinate", "0039_pre_priority_lock_fetch_job"),
        ("procrastinate", "0040_pre_retry_failed_job"),
        ("procrastinate", "0041_post_retry_failed_job"),
        ("sessions", "0001_initial"),
        ("token_blacklist", "0001_initial"),
        ("token_blacklist", "0002_outstandingtoken_jti_hex"),
        ("token_blacklist", "0003_auto_20171017_2007"),
        ("token_blacklist", "0004_auto_20171017_2013"),
        ("token_blacklist", "0005_remove_outstandingtoken_jti"),
        ("token_blacklist", "0006_auto_20171017_2113"),
        ("token_blacklist", "0007_auto_20171017_2214"),
        ("token_blacklist", "0008_migrate_to_bigautofield"),
        ("token_blacklist", "0010_fix_migrate_to_bigautofield"),
        ("token_blacklist", "0011_linearizes_history"),
        ("token_blacklist", "0012_alter_outstandingtoken_user"),
        ("token_blacklist", "0013_alter_blacklistedtoken_options_and_more"),
    }
)

ALIASES = {("shared", "0015_scoped_grants_queue_prerequisite"): ("shared", "0008_scoped_role_table_grants")}

BASELINE_PHASES = {
    ("assets", "0001_baseline"): {
        "replaces": frozenset(
            {
                ("assets", "0001_initial"),
                ("assets", "0002_add_ledova_aaud_asset"),
                ("assets", "0003_rename_aaud_asset"),
                ("assets", "0004_deactivate_unsupported_assets"),
                ("assets", "0005_add_asset_chain_deployment"),
                ("assets", "0006_populate_chain_deployments"),
                ("assets", "0007_remove_asset_chain_contract"),
                ("assets", "0008_asset_is_verified"),
                ("assets", "0009_verify_supported_assets_cleanup_spam"),
                ("assets", "0010_alter_asset_asset_type_alter_asset_current_price_and_more"),
                ("assets", "0011_add_exchange_rate_model"),
                ("assets", "0012_audy_base_deployment"),
                ("assets", "0013_price_provenance"),
                ("assets", "0014_native_chain_deployments"),
            }
        ),
        "requires": frozenset(),
    },
    ("authentication", "0001_baseline"): {
        "replaces": frozenset(
            {
                ("authentication", "0001_initial"),
                ("authentication", "0002_authsession_refreshcredential"),
                ("authentication", "0003_customuser_v2_email_constraints"),
                ("authentication", "0004_v2_challenge_schema"),
                ("authentication", "0005_auth_del_superseded_proof_shapes"),
                ("authentication", "0006_delete_v2_challenge_models"),
                ("authentication", "0007_delete_authsession_refreshcredential"),
                ("authentication", "0008_delete_usertoken"),
                ("authentication", "0009_otp_attempts_drop_unused_columns"),
            }
        ),
        "requires": frozenset(
            {
                ("auth", "0001_initial"),
                ("auth", "0002_alter_permission_name_max_length"),
                ("auth", "0003_alter_user_email_max_length"),
                ("auth", "0004_alter_user_username_opts"),
                ("auth", "0005_alter_user_last_login_null"),
                ("auth", "0006_require_contenttypes_0002"),
                ("auth", "0007_alter_validators_add_error_messages"),
                ("auth", "0008_alter_user_username_max_length"),
                ("auth", "0009_alter_user_last_name_max_length"),
                ("auth", "0010_alter_group_name_max_length"),
                ("auth", "0011_update_proxy_permissions"),
                ("auth", "0012_alter_user_first_name_max_length"),
                ("contenttypes", "0001_initial"),
                ("contenttypes", "0002_remove_content_type_name"),
            }
        ),
    },
    ("blockchain", "0001_baseline"): {
        "replaces": frozenset(
            {
                ("blockchain", "0001_initial"),
                ("blockchain", "0002_alter_blockchaintransaction_tx_type"),
                ("blockchain", "0003_delete_contractdeployment"),
                ("blockchain", "0004_durable_outgoing"),
                ("blockchain", "0005_legacy_outgoing_inventory"),
                ("blockchain", "0006_signer_admission"),
                ("blockchain", "0007_transaction_outgoing_operation"),
                ("blockchain", "0008_fresh_signer_bootstrap"),
            }
        ),
        "requires": frozenset(),
    },
    ("companies", "0001_baseline"): {
        "replaces": frozenset(
            {
                ("companies", "0001_initial"),
                ("companies", "0002_company_owner_required"),
                ("companies", "0003_delete_review_and_signature_models"),
                ("companies", "0004_company_additional_info_response"),
                ("companies", "0005_company_is_open_to_investors"),
                ("companies", "0006_company_document_private_storage"),
                ("companies", "0007_alter_company_abn_alter_company_acn"),
                ("companies", "0008_company_registry_verification"),
                ("companies", "0009_document_verification"),
                ("companies", "0010_company_pack"),
                ("companies", "0011_remove_company_api_key"),
                ("companies", "0012_company_authority_request"),
                ("companies", "0013_company_authority_request_withdrawal"),
                ("companies", "0014_authority_request_capabilities_refuse_null"),
                ("companies", "0015_self_declared_company_appointments"),
                ("companies", "0016_appointee_keyed_appointments"),
                ("companies", "0017_company_team_invitations"),
                ("companies", "0018_team_invitation_admission_guards"),
                ("companies", "0019_legacy_owner_appointments"),
                ("companies", "0020_company_administration"),
                ("companies", "0021_company_activation"),
            }
        ),
        "requires": frozenset(
            {
                ("auth", "0001_initial"),
                ("auth", "0002_alter_permission_name_max_length"),
                ("auth", "0003_alter_user_email_max_length"),
                ("auth", "0004_alter_user_username_opts"),
                ("auth", "0005_alter_user_last_login_null"),
                ("auth", "0006_require_contenttypes_0002"),
                ("auth", "0007_alter_validators_add_error_messages"),
                ("auth", "0008_alter_user_username_max_length"),
                ("auth", "0009_alter_user_last_name_max_length"),
                ("auth", "0010_alter_group_name_max_length"),
                ("auth", "0011_update_proxy_permissions"),
                ("auth", "0012_alter_user_first_name_max_length"),
                ("authentication", "0001_baseline"),
                ("contenttypes", "0001_initial"),
                ("contenttypes", "0002_remove_content_type_name"),
            }
        ),
    },
    ("companies", "0002_baseline"): {
        "replaces": frozenset({("companies", "0022_company_wallet_lock_order")}),
        "requires": frozenset(
            {
                ("assets", "0001_baseline"),
                ("auth", "0001_initial"),
                ("auth", "0002_alter_permission_name_max_length"),
                ("auth", "0003_alter_user_email_max_length"),
                ("auth", "0004_alter_user_username_opts"),
                ("auth", "0005_alter_user_last_login_null"),
                ("auth", "0006_require_contenttypes_0002"),
                ("auth", "0007_alter_validators_add_error_messages"),
                ("auth", "0008_alter_user_username_max_length"),
                ("auth", "0009_alter_user_last_name_max_length"),
                ("auth", "0010_alter_group_name_max_length"),
                ("auth", "0011_update_proxy_permissions"),
                ("auth", "0012_alter_user_first_name_max_length"),
                ("authentication", "0001_baseline"),
                ("blockchain", "0001_baseline"),
                ("companies", "0001_baseline"),
                ("contenttypes", "0001_initial"),
                ("contenttypes", "0002_remove_content_type_name"),
                ("offerings", "0001_baseline"),
                ("shared", "0001_baseline"),
                ("tokens", "0001_baseline"),
                ("users", "0001_baseline"),
                ("wallets", "0001_baseline"),
            }
        ),
    },
    ("compliance", "0001_baseline"): {
        "replaces": frozenset(
            {
                ("compliance", "0001_initial"),
                ("compliance", "0002_initial"),
                ("compliance", "0003_add_provider_field"),
                ("compliance", "0004_remove_sumsub_transaction_id"),
                ("compliance", "0005_remove_fiat_transaction_and_high_risk_country"),
                ("compliance", "0006_pep_and_watchlist_match_alerts"),
                ("compliance", "0007_approved_pep_without_category"),
            }
        ),
        "requires": frozenset(
            {
                ("assets", "0001_baseline"),
                ("auth", "0001_initial"),
                ("auth", "0002_alter_permission_name_max_length"),
                ("auth", "0003_alter_user_email_max_length"),
                ("auth", "0004_alter_user_username_opts"),
                ("auth", "0005_alter_user_last_login_null"),
                ("auth", "0006_require_contenttypes_0002"),
                ("auth", "0007_alter_validators_add_error_messages"),
                ("auth", "0008_alter_user_username_max_length"),
                ("auth", "0009_alter_user_last_name_max_length"),
                ("auth", "0010_alter_group_name_max_length"),
                ("auth", "0011_update_proxy_permissions"),
                ("auth", "0012_alter_user_first_name_max_length"),
                ("authentication", "0001_baseline"),
                ("blockchain", "0001_baseline"),
                ("companies", "0001_baseline"),
                ("contenttypes", "0001_initial"),
                ("contenttypes", "0002_remove_content_type_name"),
                ("offerings", "0001_baseline"),
                ("shared", "0001_baseline"),
                ("tokens", "0001_baseline"),
                ("users", "0001_baseline"),
                ("wallets", "0001_baseline"),
            }
        ),
    },
    ("documents", "0001_baseline"): {
        "replaces": frozenset(
            {
                ("documents", "0001_initial"),
                ("documents", "0002_document_private_storage"),
                ("documents", "0003_documentread_document_attached_at_and_more"),
            }
        ),
        "requires": frozenset(
            {
                ("assets", "0001_baseline"),
                ("auth", "0001_initial"),
                ("auth", "0002_alter_permission_name_max_length"),
                ("auth", "0003_alter_user_email_max_length"),
                ("auth", "0004_alter_user_username_opts"),
                ("auth", "0005_alter_user_last_login_null"),
                ("auth", "0006_require_contenttypes_0002"),
                ("auth", "0007_alter_validators_add_error_messages"),
                ("auth", "0008_alter_user_username_max_length"),
                ("auth", "0009_alter_user_last_name_max_length"),
                ("auth", "0010_alter_group_name_max_length"),
                ("auth", "0011_update_proxy_permissions"),
                ("auth", "0012_alter_user_first_name_max_length"),
                ("authentication", "0001_baseline"),
                ("blockchain", "0001_baseline"),
                ("companies", "0001_baseline"),
                ("contenttypes", "0001_initial"),
                ("contenttypes", "0002_remove_content_type_name"),
                ("offerings", "0001_baseline"),
                ("shared", "0001_baseline"),
                ("tokens", "0001_baseline"),
                ("users", "0001_baseline"),
            }
        ),
    },
    ("feature_flags", "0001_baseline"): {
        "replaces": frozenset(
            {
                ("feature_flags", "0001_initial"),
                ("feature_flags", "0002_add_trading_enabled_flag"),
                ("feature_flags", "0003_enable_trading_by_default"),
            }
        ),
        "requires": frozenset(),
    },
    ("offerings", "0001_baseline"): {
        "replaces": frozenset(
            {
                ("offerings", "0001_initial"),
                ("offerings", "0002_subscription"),
                ("offerings", "0003_subscription_tx_hash_case_insensitive"),
                ("offerings", "0004_protect_the_offering_token"),
                ("offerings", "0005_r0_owner_columns"),
                ("offerings", "0006_trigger_follows_and_refuses"),
                ("offerings", "0007_subscription_step_times"),
                ("offerings", "0008_subscription_snapshots"),
                ("offerings", "0009_published_documents_stay"),
            }
        ),
        "requires": frozenset(
            {
                ("assets", "0001_baseline"),
                ("auth", "0001_initial"),
                ("auth", "0002_alter_permission_name_max_length"),
                ("auth", "0003_alter_user_email_max_length"),
                ("auth", "0004_alter_user_username_opts"),
                ("auth", "0005_alter_user_last_login_null"),
                ("auth", "0006_require_contenttypes_0002"),
                ("auth", "0007_alter_validators_add_error_messages"),
                ("auth", "0008_alter_user_username_max_length"),
                ("auth", "0009_alter_user_last_name_max_length"),
                ("auth", "0010_alter_group_name_max_length"),
                ("auth", "0011_update_proxy_permissions"),
                ("auth", "0012_alter_user_first_name_max_length"),
                ("authentication", "0001_baseline"),
                ("companies", "0001_baseline"),
                ("contenttypes", "0001_initial"),
                ("contenttypes", "0002_remove_content_type_name"),
            }
        ),
    },
    ("offerings", "0002_baseline"): {
        "replaces": frozenset({("offerings", "0010_company_eligibility_admission")}),
        "requires": frozenset(
            {
                ("assets", "0001_baseline"),
                ("auth", "0001_initial"),
                ("auth", "0002_alter_permission_name_max_length"),
                ("auth", "0003_alter_user_email_max_length"),
                ("auth", "0004_alter_user_username_opts"),
                ("auth", "0005_alter_user_last_login_null"),
                ("auth", "0006_require_contenttypes_0002"),
                ("auth", "0007_alter_validators_add_error_messages"),
                ("auth", "0008_alter_user_username_max_length"),
                ("auth", "0009_alter_user_last_name_max_length"),
                ("auth", "0010_alter_group_name_max_length"),
                ("auth", "0011_update_proxy_permissions"),
                ("auth", "0012_alter_user_first_name_max_length"),
                ("authentication", "0001_baseline"),
                ("blockchain", "0001_baseline"),
                ("companies", "0001_baseline"),
                ("companies", "0002_baseline"),
                ("contenttypes", "0001_initial"),
                ("contenttypes", "0002_remove_content_type_name"),
                ("offerings", "0001_baseline"),
                ("shared", "0001_baseline"),
                ("tokens", "0001_baseline"),
                ("users", "0001_baseline"),
                ("wallets", "0001_baseline"),
            }
        ),
    },
    ("operators", "0001_baseline"): {
        "replaces": frozenset({("operators", "0001_initial"), ("operators", "0002_remove_operator_deployment_mode")}),
        "requires": frozenset({("assets", "0001_baseline")}),
    },
    ("portfolios", "0001_baseline"): {
        "replaces": frozenset(
            {
                ("portfolios", "0001_initial"),
                ("portfolios", "0002_initial"),
                ("portfolios", "0003_remove_portfolio_template_and_target_asset_allocation"),
                ("portfolios", "0004_delete_assetallocation"),
                ("portfolios", "0005_delete_portfoliosnapshot"),
            }
        ),
        "requires": frozenset(
            {
                ("assets", "0001_baseline"),
                ("auth", "0001_initial"),
                ("auth", "0002_alter_permission_name_max_length"),
                ("auth", "0003_alter_user_email_max_length"),
                ("auth", "0004_alter_user_username_opts"),
                ("auth", "0005_alter_user_last_login_null"),
                ("auth", "0006_require_contenttypes_0002"),
                ("auth", "0007_alter_validators_add_error_messages"),
                ("auth", "0008_alter_user_username_max_length"),
                ("auth", "0009_alter_user_last_name_max_length"),
                ("auth", "0010_alter_group_name_max_length"),
                ("auth", "0011_update_proxy_permissions"),
                ("auth", "0012_alter_user_first_name_max_length"),
                ("authentication", "0001_baseline"),
                ("blockchain", "0001_baseline"),
                ("companies", "0001_baseline"),
                ("contenttypes", "0001_initial"),
                ("contenttypes", "0002_remove_content_type_name"),
                ("offerings", "0001_baseline"),
                ("shared", "0001_baseline"),
                ("tokens", "0001_baseline"),
                ("users", "0001_baseline"),
                ("wallets", "0001_baseline"),
            }
        ),
    },
    ("shared", "0001_baseline"): {
        "replaces": frozenset(
            {
                ("shared", "0001_initial"),
                ("shared", "0002_drop_celery_tables"),
                ("shared", "0003_rls_roles_and_grants"),
                ("shared", "0004_rls_policies"),
                ("shared", "0005_rls_principal_missing_ok"),
                ("shared", "0006_account_insert_by_director"),
                ("shared", "0007_review_request_policies"),
                ("shared", "0008_scoped_role_table_grants"),
                ("shared", "0009_policies_require_a_principal"),
                ("shared", "0010_policies_for_the_tables_that_had_none"),
                ("shared", "0011_the_helper_names_the_principal"),
                ("shared", "0012_operator_creates_matches"),
                ("shared", "0013_policies_without_the_dropped_tables"),
            }
        ),
        "requires": frozenset(),
    },
    ("shared", "0002_baseline_security"): {
        "replaces": frozenset({("shared", "0014_policies_without_notification_preferences")}),
        "requires": frozenset(
            {
                ("admin", "0001_initial"),
                ("admin", "0002_logentry_remove_auto_add"),
                ("admin", "0003_logentry_add_action_flag_choices"),
                ("assets", "0001_baseline"),
                ("auth", "0001_initial"),
                ("auth", "0002_alter_permission_name_max_length"),
                ("auth", "0003_alter_user_email_max_length"),
                ("auth", "0004_alter_user_username_opts"),
                ("auth", "0005_alter_user_last_login_null"),
                ("auth", "0006_require_contenttypes_0002"),
                ("auth", "0007_alter_validators_add_error_messages"),
                ("auth", "0008_alter_user_username_max_length"),
                ("auth", "0009_alter_user_last_name_max_length"),
                ("auth", "0010_alter_group_name_max_length"),
                ("auth", "0011_update_proxy_permissions"),
                ("auth", "0012_alter_user_first_name_max_length"),
                ("authentication", "0001_baseline"),
                ("blockchain", "0001_baseline"),
                ("companies", "0001_baseline"),
                ("companies", "0002_baseline"),
                ("compliance", "0001_baseline"),
                ("contenttypes", "0001_initial"),
                ("contenttypes", "0002_remove_content_type_name"),
                ("documents", "0001_baseline"),
                ("feature_flags", "0001_baseline"),
                ("offerings", "0001_baseline"),
                ("offerings", "0002_baseline"),
                ("operators", "0001_baseline"),
                ("portfolios", "0001_baseline"),
                ("procrastinate", "0001_initial"),
                ("procrastinate", "0002_drop_started_at_column"),
                ("procrastinate", "0003_drop_started_at_column"),
                ("procrastinate", "0004_drop_procrastinate_version_table"),
                ("procrastinate", "0005_fix_procrastinate_fetch_job"),
                ("procrastinate", "0006_fix_trigger_status_events_insert"),
                ("procrastinate", "0007_add_queueing_lock_column"),
                ("procrastinate", "0008_close_fetch_job_race_condition"),
                ("procrastinate", "0009_add_defer_job_function"),
                ("procrastinate", "0010_add_procrastinate_periodic_defers"),
                ("procrastinate", "0011_add_foreign_key_index"),
                ("procrastinate", "0012_add_locks_to_periodic_defer"),
                ("procrastinate", "0013_fix_procrastinate_defer_periodic_job"),
                ("procrastinate", "0014_add_finish_job_and_retry_job_functions"),
                ("procrastinate", "0015_add_trigger_on_job_deletion"),
                ("procrastinate", "0016_delete_finished_jobs"),
                ("procrastinate", "0017_add_checks_to_finish_job"),
                ("procrastinate", "0018_add_checks_to_retry_job"),
                ("procrastinate", "0019_fix_finish_job_compat_issue"),
                ("procrastinate", "0020_add_index_on_procrastinate_jobs"),
                ("procrastinate", "0021_add_kwargs_to_defer_periodic_job"),
                ("procrastinate", "0022_null_locks_excluded"),
                ("procrastinate", "0023_remove_old_finish_job_function"),
                ("procrastinate", "0024_job_id_bigint"),
                ("procrastinate", "0025_add_models"),
                ("procrastinate", "0026_add_job_priority"),
                ("procrastinate", "0027_add_periodic_job_priority"),
                ("procrastinate", "0028_add_cancel_states"),
                ("procrastinate", "0029_add_additional_params_to_retry_job"),
                ("procrastinate", "0030_alter_procrastinateevent_options"),
                ("procrastinate", "0031_add_indexes_for_fetch_job"),
                ("procrastinate", "0032_pre_cancel_notification"),
                ("procrastinate", "0033_post_cancel_notification"),
                ("procrastinate", "0034_pre_add_heartbeat"),
                ("procrastinate", "0035_post_add_heartbeat"),
                ("procrastinate", "0036_add_worker_model"),
                ("procrastinate", "0037_pre_batch_defer_jobs"),
                ("procrastinate", "0038_post_batch_defer_jobs"),
                ("procrastinate", "0039_pre_priority_lock_fetch_job"),
                ("procrastinate", "0040_pre_retry_failed_job"),
                ("procrastinate", "0041_post_retry_failed_job"),
                ("sessions", "0001_initial"),
                ("shared", "0001_baseline"),
                ("shareholders", "0001_baseline"),
                ("token_blacklist", "0001_initial"),
                ("token_blacklist", "0002_outstandingtoken_jti_hex"),
                ("token_blacklist", "0003_auto_20171017_2007"),
                ("token_blacklist", "0004_auto_20171017_2013"),
                ("token_blacklist", "0005_remove_outstandingtoken_jti"),
                ("token_blacklist", "0006_auto_20171017_2113"),
                ("token_blacklist", "0007_auto_20171017_2214"),
                ("token_blacklist", "0008_migrate_to_bigautofield"),
                ("token_blacklist", "0010_fix_migrate_to_bigautofield"),
                ("token_blacklist", "0011_linearizes_history"),
                ("token_blacklist", "0012_alter_outstandingtoken_user"),
                ("token_blacklist", "0013_alter_blacklistedtoken_options_and_more"),
                ("tokens", "0001_baseline"),
                ("tokens", "0002_baseline"),
                ("users", "0001_baseline"),
                ("wallets", "0001_baseline"),
                ("whitelist", "0001_baseline"),
            }
        ),
    },
    ("shareholders", "0001_baseline"): {
        "replaces": frozenset(
            {
                ("shareholders", "0001_publications"),
                ("shareholders", "0002_publication_names_its_company_and_class"),
                ("shareholders", "0003_resolutions"),
                ("shareholders", "0004_distributions"),
                ("shareholders", "0005_publication_event_preimage"),
                ("shareholders", "0006_publication_to_a_paused_class"),
            }
        ),
        "requires": frozenset(
            {
                ("assets", "0001_baseline"),
                ("auth", "0001_initial"),
                ("auth", "0002_alter_permission_name_max_length"),
                ("auth", "0003_alter_user_email_max_length"),
                ("auth", "0004_alter_user_username_opts"),
                ("auth", "0005_alter_user_last_login_null"),
                ("auth", "0006_require_contenttypes_0002"),
                ("auth", "0007_alter_validators_add_error_messages"),
                ("auth", "0008_alter_user_username_max_length"),
                ("auth", "0009_alter_user_last_name_max_length"),
                ("auth", "0010_alter_group_name_max_length"),
                ("auth", "0011_update_proxy_permissions"),
                ("auth", "0012_alter_user_first_name_max_length"),
                ("authentication", "0001_baseline"),
                ("blockchain", "0001_baseline"),
                ("companies", "0001_baseline"),
                ("companies", "0002_baseline"),
                ("contenttypes", "0001_initial"),
                ("contenttypes", "0002_remove_content_type_name"),
                ("offerings", "0001_baseline"),
                ("shared", "0001_baseline"),
                ("tokens", "0001_baseline"),
                ("users", "0001_baseline"),
                ("wallets", "0001_baseline"),
            }
        ),
    },
    ("tokens", "0001_baseline"): {
        "replaces": frozenset(
            {
                ("tokens", "0001_initial"),
                ("tokens", "0002_yield_token_and_nav"),
                ("tokens", "0003_unify_mint_request"),
                ("tokens", "0004_seed_ausg_yield_token"),
                ("tokens", "0005_rename_token_issuance_to_share_issuance"),
                ("tokens", "0006_rename_tokens_stab_status_4c5fd9_idx_tokens_mint_status_99ebab_idx_and_more"),
                ("tokens", "0007_stablecoin_reserve_fields"),
                ("tokens", "0008_share_issuance_request"),
                ("tokens", "0009_transferorder_ownership"),
                ("tokens", "0010_transferorder_bind_legacy_orders"),
                ("tokens", "0011_transferorder_owner_required"),
                ("tokens", "0012_reviewable_request"),
                ("tokens", "0013_remove_transferorder_signature_request"),
                ("tokens", "0014_settlement_asset_columns"),
                ("tokens", "0015_fold_stablecoin_into_asset"),
                ("tokens", "0016_drop_stablecoin"),
                ("tokens", "0017_share_token_chain"),
                ("tokens", "0018_protect_the_register_spine"),
                ("tokens", "0019_signing_challenge"),
                ("tokens", "0020_shareissuance_identity_stamped_at_and_more"),
                ("tokens", "0021_modification_log_names_its_challenge"),
                ("tokens", "0022_swap_nonce_is_unique"),
                ("tokens", "0023_r0_owner_columns"),
                ("tokens", "0024_r0_sharetoken_owner"),
                ("tokens", "0025_a_token_cannot_change_company"),
                ("tokens", "0026_one_capital_increase_in_flight"),
                ("tokens", "0029_execution_notes"),
                ("tokens", "0030_superseded_capital_increase"),
                ("tokens", "0031_share_tokens_have_zero_decimals"),
                ("tokens", "0032_former_holders"),
                ("tokens", "0033_the_fold_records_where_it_reached"),
                ("tokens", "0034_shareissuance_mint_journal"),
                ("tokens", "0035_trading_state_invariants"),
                ("tokens", "0036_swap_expiry_eligibility"),
                ("tokens", "0037_order_submissions"),
                ("tokens", "0038_order_action_submissions"),
                ("tokens", "0039_swap_settlement_context"),
                ("tokens", "0040_swap_parent_identity"),
                ("tokens", "0041_drop_the_token_owner_no_policy_reads"),
                ("tokens", "0042_mint_request_operations"),
                ("tokens", "0043_token_deployment"),
                ("tokens", "0044_token_deployment_guards"),
                ("tokens", "0045_capital_increase_execution"),
                ("tokens", "0046_capital_execution_guards"),
                ("tokens", "0047_issuance_execution"),
                ("tokens", "0048_issuance_execution_guards"),
                ("tokens", "0049_swap_approval_phase"),
                ("tokens", "0050_swap_approval_guards"),
                ("tokens", "0051_pause_change"),
                ("tokens", "0052_pause_change_guards"),
                ("tokens", "0053_nav_update_recovery"),
                ("tokens", "0054_nav_update_guards"),
                ("tokens", "0055_order_submission_settlement_refusal"),
                ("tokens", "0056_hold_legacy_swaps"),
                ("tokens", "0057_swap_execution_guards"),
                ("tokens", "0058_swap_finality_completion"),
                ("tokens", "0059_swap_approval_submission"),
                ("tokens", "0060_order_submission_settlement_chain_refusal"),
                ("tokens", "0061_swap_approval_recovery_index"),
                ("tokens", "0062_register_foundation"),
                ("tokens", "0063_swap_finalized_receipt"),
                ("tokens", "0064_reviewed_register_corrections"),
                ("tokens", "0065_register_opening"),
                ("tokens", "0066_issuance_finality_and_boundary_history"),
                ("tokens", "0067_register_wallet_links"),
                ("tokens", "0068_completion_transaction_index"),
                ("tokens", "0069_opening_mapping_values"),
                ("tokens", "0070_register_reconciliation"),
                ("tokens", "0071_register_export_audit"),
                ("tokens", "0072_register_import"),
                ("tokens", "0073_register_instructions"),
                ("tokens", "0074_register_inspection_copies"),
                ("tokens", "0075_register_certificates"),
                ("tokens", "0076_transfer_instructions"),
                ("tokens", "0077_import_opening"),
                ("tokens", "0078_register_notice_figures"),
                ("tokens", "0079_order_submission_eligibility_refusal"),
                ("tokens", "0080_company_pack"),
                ("tokens", "0081_held_orders_and_retired_statuses"),
                ("tokens", "0082_company_eligibility_admission"),
                ("tokens", "0083_company_register_imports"),
                ("tokens", "0084_company_register_import_guards"),
                ("tokens", "0085_company_register_corrections"),
                ("tokens", "0086_company_register_correction_guards"),
                ("tokens", "0087_company_discrepancy_acknowledgements"),
                ("tokens", "0088_company_register_openings"),
                ("tokens", "0089_company_register_opening_guards"),
                ("tokens", "0090_company_particulars_changes"),
                ("tokens", "0091_company_particulars_change_guards"),
                ("tokens", "0092_company_register_wallet_links"),
                ("tokens", "0093_company_register_wallet_link_guards"),
                ("tokens", "0094_company_register_grants"),
                ("tokens", "0095_company_register_grant_guards"),
                ("tokens", "0096_company_register_transfers"),
                ("tokens", "0097_company_register_transfer_guards"),
                ("tokens", "0098_company_register_deployments"),
                ("tokens", "0099_company_register_deployment_guards"),
                ("tokens", "0100_company_register_issue_instructions"),
                ("tokens", "0101_company_register_issue_guards"),
                ("tokens", "0102_company_register_capital_increases"),
                ("tokens", "0103_company_register_capital_guards"),
                ("tokens", "0104_company_register_pause_changes"),
                ("tokens", "0105_company_register_pause_guards"),
                ("tokens", "0106_company_register_paid_issues"),
            }
        ),
        "requires": frozenset(
            {
                ("assets", "0001_baseline"),
                ("auth", "0001_initial"),
                ("auth", "0002_alter_permission_name_max_length"),
                ("auth", "0003_alter_user_email_max_length"),
                ("auth", "0004_alter_user_username_opts"),
                ("auth", "0005_alter_user_last_login_null"),
                ("auth", "0006_require_contenttypes_0002"),
                ("auth", "0007_alter_validators_add_error_messages"),
                ("auth", "0008_alter_user_username_max_length"),
                ("auth", "0009_alter_user_last_name_max_length"),
                ("auth", "0010_alter_group_name_max_length"),
                ("auth", "0011_update_proxy_permissions"),
                ("auth", "0012_alter_user_first_name_max_length"),
                ("authentication", "0001_baseline"),
                ("blockchain", "0001_baseline"),
                ("companies", "0001_baseline"),
                ("contenttypes", "0001_initial"),
                ("contenttypes", "0002_remove_content_type_name"),
            }
        ),
    },
    ("tokens", "0002_baseline"): {
        "replaces": frozenset({("tokens", "0107_company_register_paid_issue_guards")}),
        "requires": frozenset(
            {
                ("assets", "0001_baseline"),
                ("auth", "0001_initial"),
                ("auth", "0002_alter_permission_name_max_length"),
                ("auth", "0003_alter_user_email_max_length"),
                ("auth", "0004_alter_user_username_opts"),
                ("auth", "0005_alter_user_last_login_null"),
                ("auth", "0006_require_contenttypes_0002"),
                ("auth", "0007_alter_validators_add_error_messages"),
                ("auth", "0008_alter_user_username_max_length"),
                ("auth", "0009_alter_user_last_name_max_length"),
                ("auth", "0010_alter_group_name_max_length"),
                ("auth", "0011_update_proxy_permissions"),
                ("auth", "0012_alter_user_first_name_max_length"),
                ("authentication", "0001_baseline"),
                ("blockchain", "0001_baseline"),
                ("companies", "0001_baseline"),
                ("companies", "0002_baseline"),
                ("contenttypes", "0001_initial"),
                ("contenttypes", "0002_remove_content_type_name"),
                ("offerings", "0001_baseline"),
                ("offerings", "0002_baseline"),
                ("shared", "0001_baseline"),
                ("tokens", "0001_baseline"),
                ("users", "0001_baseline"),
                ("wallets", "0001_baseline"),
                ("whitelist", "0001_baseline"),
            }
        ),
    },
    ("users", "0001_baseline"): {
        "replaces": frozenset(
            {
                ("users", "0001_initial"),
                ("users", "0002_remove_userprofile_investor_type"),
                ("users", "0003_alter_userpreferences_preferred_onramp_provider"),
                ("users", "0004_create_notification_model"),
                ("users", "0005_add_kyc_provider_fields"),
                ("users", "0006_populate_kyc_provider_data"),
                ("users", "0007_userprofile_residence_country"),
                ("users", "0008_alter_userprofile_sumsub_review_answer_and_more"),
                ("users", "0009_remove_banxa_coinbase_onramp_provider"),
                ("users", "0010_remove_userpreferences_preferred_onramp_provider"),
                ("users", "0011_delete_widget"),
                ("users", "0012_useraccount_role"),
                ("users", "0013_add_theme_to_user_preferences"),
                ("users", "0014_alter_userpreferences_theme"),
                ("users", "0015_add_display_currency_preference"),
                ("users", "0016_remove_userprofile_duplicate_kyc_columns"),
                ("users", "0017_delete_waitlist"),
                ("users", "0018_investor_classification"),
                ("users", "0019_alter_investorclassification_status_and_more"),
                ("users", "0020_r0_owner_columns"),
                ("users", "0021_trigger_types_from_the_column"),
                ("users", "0022_drop_the_owner_columns_no_policy_reads"),
                ("users", "0023_one_account_per_person"),
                ("users", "0024_remove_useraccount_director"),
                ("users", "0025_remove_unread_preferences"),
                ("users", "0026_delete_favouriteasset"),
                ("users", "0027_transaction_alerts_on_user_preferences"),
                ("users", "0028_remove_theme_and_selected_portfolio"),
                ("users", "0029_first_activation_date"),
                ("users", "0029_kyc_results_in_the_fields_choices"),
                ("users", "0030_join_activation_and_kyc_results"),
                ("users", "0031_protected_identity_results"),
                ("users", "0032_company_eligibility_records"),
                ("users", "0033_company_eligibility_guards"),
                ("users", "0034_company_eligibility_consumption"),
                ("users", "0035_retire_staff_source_review"),
            }
        ),
        "requires": frozenset(
            {
                ("assets", "0001_baseline"),
                ("auth", "0001_initial"),
                ("auth", "0002_alter_permission_name_max_length"),
                ("auth", "0003_alter_user_email_max_length"),
                ("auth", "0004_alter_user_username_opts"),
                ("auth", "0005_alter_user_last_login_null"),
                ("auth", "0006_require_contenttypes_0002"),
                ("auth", "0007_alter_validators_add_error_messages"),
                ("auth", "0008_alter_user_username_max_length"),
                ("auth", "0009_alter_user_last_name_max_length"),
                ("auth", "0010_alter_group_name_max_length"),
                ("auth", "0011_update_proxy_permissions"),
                ("auth", "0012_alter_user_first_name_max_length"),
                ("authentication", "0001_baseline"),
                ("blockchain", "0001_baseline"),
                ("companies", "0001_baseline"),
                ("contenttypes", "0001_initial"),
                ("contenttypes", "0002_remove_content_type_name"),
                ("offerings", "0001_baseline"),
                ("shared", "0001_baseline"),
                ("tokens", "0001_baseline"),
            }
        ),
    },
    ("wallets", "0001_baseline"): {
        "replaces": frozenset(
            {
                ("wallets", "0001_initial"),
                ("wallets", "0002_wallet_wallet_type"),
                ("wallets", "0003_update_fiat_transaction_provider_to_transak"),
                ("wallets", "0004_wallet_is_operator"),
                ("wallets", "0005_alter_holdingsnapshot_snapshot_reason"),
                ("wallets", "0006_delete_fiattransaction_drop_unread_columns"),
                ("wallets", "0007_transaction_deducted_amount_transaction_deducted_fee"),
                ("wallets", "0008_r0_owner_column"),
                ("wallets", "0009_trigger_follows_and_refuses"),
                ("wallets", "0010_durable_state_for_a_submitted_transaction"),
                ("wallets", "0011_wallet_verification_challenge_issued_at"),
                ("wallets", "0012_balance_versions"),
                ("wallets", "0013_signing_preference"),
                ("wallets", "0014_wallet_network_identity"),
                ("wallets", "0015_transaction_imported_from_history"),
                ("wallets", "0016_wallet_submission"),
                ("wallets", "0017_bitcoin_submission"),
                ("wallets", "0018_global_submission_identity"),
                ("wallets", "0019_chain_observations"),
                ("wallets", "0020_transaction_monitoring_completed_at"),
                ("wallets", "0021_transaction_finality_observation"),
                ("wallets", "0022_delete_holdingsnapshot"),
                ("wallets", "0023_transaction_market_value_aud"),
                ("wallets", "0024_wallet_possession_proof"),
                ("wallets", "0025_wallet_possession_proof_guards"),
            }
        ),
        "requires": frozenset(
            {
                ("assets", "0001_baseline"),
                ("auth", "0001_initial"),
                ("auth", "0002_alter_permission_name_max_length"),
                ("auth", "0003_alter_user_email_max_length"),
                ("auth", "0004_alter_user_username_opts"),
                ("auth", "0005_alter_user_last_login_null"),
                ("auth", "0006_require_contenttypes_0002"),
                ("auth", "0007_alter_validators_add_error_messages"),
                ("auth", "0008_alter_user_username_max_length"),
                ("auth", "0009_alter_user_last_name_max_length"),
                ("auth", "0010_alter_group_name_max_length"),
                ("auth", "0011_update_proxy_permissions"),
                ("auth", "0012_alter_user_first_name_max_length"),
                ("authentication", "0001_baseline"),
                ("blockchain", "0001_baseline"),
                ("companies", "0001_baseline"),
                ("contenttypes", "0001_initial"),
                ("contenttypes", "0002_remove_content_type_name"),
                ("offerings", "0001_baseline"),
                ("shared", "0001_baseline"),
                ("tokens", "0001_baseline"),
                ("users", "0001_baseline"),
            }
        ),
    },
    ("whitelist", "0001_baseline"): {
        "replaces": frozenset(
            {
                ("whitelist", "0001_initial"),
                ("whitelist", "0002_whitelistentry_treasury_addresses"),
                ("whitelist", "0003_whitelistentry_unique_treasury_address"),
                ("whitelist", "0004_failure_reconciled_at"),
                ("whitelist", "0005_whitelist_change"),
                ("whitelist", "0006_whitelist_change_guards"),
                ("whitelist", "0007_per_company_approvals"),
                ("whitelist", "0008_classification_refresh_authority"),
                ("whitelist", "0009_company_eligibility_invalidation"),
                ("whitelist", "0010_company_wallet_instructions"),
                ("whitelist", "0011_company_wallet_instruction_guards"),
            }
        ),
        "requires": frozenset(
            {
                ("assets", "0001_baseline"),
                ("auth", "0001_initial"),
                ("auth", "0002_alter_permission_name_max_length"),
                ("auth", "0003_alter_user_email_max_length"),
                ("auth", "0004_alter_user_username_opts"),
                ("auth", "0005_alter_user_last_login_null"),
                ("auth", "0006_require_contenttypes_0002"),
                ("auth", "0007_alter_validators_add_error_messages"),
                ("auth", "0008_alter_user_username_max_length"),
                ("auth", "0009_alter_user_last_name_max_length"),
                ("auth", "0010_alter_group_name_max_length"),
                ("auth", "0011_update_proxy_permissions"),
                ("auth", "0012_alter_user_first_name_max_length"),
                ("authentication", "0001_baseline"),
                ("blockchain", "0001_baseline"),
                ("companies", "0001_baseline"),
                ("contenttypes", "0001_initial"),
                ("contenttypes", "0002_remove_content_type_name"),
                ("offerings", "0001_baseline"),
                ("shared", "0001_baseline"),
                ("tokens", "0001_baseline"),
                ("users", "0001_baseline"),
                ("wallets", "0001_baseline"),
            }
        ),
    },
}
