from contextlib import nullcontext

import pymupdf
from django.core.files.base import ContentFile

from companies.models import CompanyDocument, DocumentType
from companies.services.document_review import prepare_document_review, verify_document
from shared.seeds.synthetic.clock import frozen
from shared.seeds.synthetic.identities import slug

SYNTHETIC_NOTICE = "Synthetic demonstration document generated by seed_demo. Not a real record."
PDF = "application/pdf"
RESOLUTION = "Directors' resolution"


def pdf(title, lines):
    with pymupdf.open() as document:
        page = document.new_page(width=595, height=842)
        page.insert_text((56, 72), title, fontsize=16)
        offset = 112
        for line in lines:
            page.insert_text((56, offset), line, fontsize=10)
            offset += 16
        page.insert_text((56, 800), SYNTHETIC_NOTICE, fontsize=8)
        return document.tobytes(no_new_id=True, garbage=3, deflate=True)


def acn_text(acn):
    return f"ACN {acn[:3]} {acn[3:6]} {acn[6:]}"


def _at(moment):
    return frozen(moment) if moment else nullcontext()


def company_document(company, document_type, name, content, *, at=None, valid_from=None):
    with _at(at):
        document = CompanyDocument(
            company=company,
            document_type=document_type,
            name=name,
            file_size=len(content),
            mime_type=PDF,
            valid_from=valid_from,
        )
        document.file.save(name, ContentFile(content), save=True)
    return document


def verified(document, reviewer, *, at=None):
    with _at(at):
        _, confirmation = prepare_document_review(document_id=document.pk, reviewer=reviewer)
        return verify_document(document_id=document.pk, reviewer=reviewer, confirmation=confirmation)


def authority(company, purpose, title, lines, reviewer, *, at=None):
    content = pdf(f"{RESOLUTION}: {title}", [company.name, acn_text(company.acn), *lines])
    name = f"{slug(company.trading_name or company.name)}-{purpose}.pdf"
    return verified(company_document(company, DocumentType.OTHER, name, content, at=at), reviewer, at=at)
