import pymupdf

SYNTHETIC_NOTICE = "Synthetic demonstration document generated by seed_demo. Not a real record."


def pdf(title, lines):
    with pymupdf.open() as document:
        page = document.new_page(width=595, height=842)
        page.insert_text((56, 72), title, fontsize=16)
        offset = 112
        for line in lines:
            page.insert_text((56, offset), line, fontsize=10)
            offset += 16
        page.insert_text((56, 800), SYNTHETIC_NOTICE, fontsize=8)
        return document.tobytes(no_new_id=True, garbage=3, deflate=True)
