from zoneinfo import ZoneInfo

MAX_ORDER_ACTION_QUANTITY = 2**63 - 1
MAX_SETTLEMENT_UNITS = 2**63 - 1
MAX_UINT256 = 2**256 - 1
ORDER_ACTION_REFUSAL_DETAIL_LIMIT = 512

MINT_RECOVERY_BATCH = 100
DEPLOYMENT_RECOVERY_BATCH = 100
PAUSE_RECOVERY_BATCH = 100
CAPITAL_RECOVERY_BATCH = 100
ISSUANCE_RECOVERY_BATCH = 100
ISSUANCE_RECOVERY_COLLISION_RETRIES = 3
MINT_CHAIN = "base"

NAV_RECOVERY_BATCH = 100

SWAP_EXECUTION_RECOVERY_BATCH = 100
MAX_SWAP_RECEIPT_VALUE = 2**31 - 1

SWAP_APPROVAL_RECOVERY_BATCH = 100
SWAP_APPROVAL_RECEIPT_WAIT_SECONDS = 5
SWAP_APPROVAL_RESEND_SECONDS = 60

REGISTER_CORRECTION_REVIEW_MAX_AGE = 900
REGISTER_OPENING_REVIEW_MAX_AGE = 900
REGISTER_LINK_REVIEW_MAX_AGE = 900
REGISTER_IMPORT_REVIEW_MAX_AGE = 900
REGISTER_IMPORT_ADDRESS_LENGTH = 1000
REGISTER_INSTRUCTION_REVIEW_MAX_AGE = 900

INSPECTION_COPY_DAYS = 7
STATUTORY_CALENDAR = ZoneInfo("Australia/Sydney")
CERTIFICATE_MARGIN = 56
