MAX_ORDER_ACTION_QUANTITY = 2**63 - 1
MAX_SETTLEMENT_UNITS = 2**63 - 1
ORDER_ACTION_REFUSAL_DETAIL_LIMIT = 512

MINT_RECOVERY_BATCH = 100
DEPLOYMENT_RECOVERY_BATCH = 100
PAUSE_RECOVERY_BATCH = 100
CAPITAL_RECOVERY_BATCH = 100
ISSUANCE_RECOVERY_BATCH = 100
ISSUANCE_RECOVERY_COLLISION_RETRIES = 3
MINT_CHAIN = "base"

NAV_RECOVERY_BATCH = 100
